[workspace]
resolver = "2"
members = [
    "crates/teams-core",
    "crates/teams-mcp-server",
    "crates/teams-mcp-stdio",
    "crates/teams-mcp-http",
]

[workspace.package]
edition = "2021"
version = "0.1.2"
license = "MIT"

[workspace.dependencies]
teams-core = { path = "crates/teams-core" }
teams-mcp-server = { path = "crates/teams-mcp-server" }
rmcp = { version = "2.2", features = ["server", "macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"

[profile.release]
strip = true
lto = true
opt-level = "z"
